services:
  odoo:
    container_name: odoo
    image: odoo:18.0
    env_file: .env
    ports:
      - "8072:8069"
    volumes:
      - ./etc/odoo:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./var/lib/odoo:/var/lib/odoo
    depends_on:
      - odoo-postgres
    networks:
      - odoo-network

  odoo-postgres:
    container_name: odoo-postgres
    image: postgres:17
    env_file: .env
    volumes:
      - ./var/lib/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - odoo-network

networks:
  odoo-network:
    driver: bridge
    
    
  